# Slicing, Referencing, and Copying Matrices

For this discussion we'll be using the NumPy library in Python (http://www.numpy.org/).

In [1]:
import numpy

Let's start with a 6x6 matrix (6 columns, 4 rows + 2 buffer rows) that we will fill with zeros,

In [13]:
COLS = 6
ROWS = 4
M=numpy.zeros((ROWS+2, COLS))

In [4]:
M

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

Now, let's take a slice out of the matrix and assign it to a new variable. We'll slice out the 3rd thru 5th rows (recall that python starts numbering at zero so row 3 thru 5 actually appears as 2:4),

In [5]:
m=M[2:4,:]

In [6]:
m

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

We'll modify are newly sliced out matrix -- say we set all values to 2,

In [14]:
m[:]=2
m

array([[ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.]])

Notice the original matrix, M, has been modified!

In [9]:
M

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

Apparently, the assignment operator, =, simply creates a reference to $\texttt{M[2:4,:]}$. To create a copy we could use $\texttt{numpy.copy()}$ as in

In [12]:
N=numpy.zeros((ROWS+2, COLS));N

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
n=numpy.copy(N[2:4,:])
n

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

Again, we'll modify the newly created slice by setting all values equal to 2,

In [16]:
n[:]=2

In [19]:
N

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [20]:
n

array([[ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.,  2.]])

As we've shown, the assignment operator merely makes a reference to the same object (location in memory) whereas numpy.copy() creates an entirely new copy (elsewhere in memory).